### ISSUE TITLE
Header-Component

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#1]
## Value statement - a requirement, not a solution
As a user I need to see the current month in the Header
so that I am able to set the content of the page, such as the total amount of monthly assets and spendings, into context. 

## Description (Text, Scribble, Wireframe, Design)

![Budget Input   List of Transactions(1)](https://user-images.githubusercontent.com/67912360/91643400-2d273f80-ea33-11ea-8778-539811bb6afc.png)

## Acceptance criteria

- [x] implement as shown in wireframe
- [x] month in the Header needs to be updated regularly
- [x] needs to show local timezone 

## Tasks

- [x] Create feature branch
- [x] Add component in Storybook 
- [x] Add Header-component to App
- [x] Add expected PropTypes
- [x] Write logic to update Month and Year in Sub-Headline
- [x] Unity Tests in jest

## Size
(small)

**Comment by annaleaschroeder** [comment]
Component successfully passed code-review.
