### ISSUE TITLE
Add color coding (red, green) to transactions

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#16]
## Value statement - a requirement, not a solution

As a user
I need identify transactions at first glance as spending or income
so that I always have an overview over my budget. 

## Acceptance criteria

- [x] income = green
- [x] spending = red

## Tasks
- [x] create feature branch
- [x] associate color code with type of transaction
- [x] restyle single transaction to card without border and align timestamp and value separate from each other. 
- [x] timestamp: font color must be black
- [x] write unit test
- [x] integrate color code in storybook
- [x] write pr

## Size

(small)
