### ISSUE TITLE
Add the option to delete Transactions

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#18]
## Value statement - a requirement, not a solution

As a user 
I need to be able to delete transactions
so that I can clean up mistakes I made when adding a new transaction. 

## Description (Text, Scribble, Wireframe, Design)
- [x] Implement SVG showing a bin as a button to enable the user to delete transactions

## Acceptance criteria

- [x] The user must be able to delete transactions by clicking on a button displayed as a bin. 

## Tasks

- [x] create feature branch
- [x] search for adequate svg image of bin
- [x] include svg as button to delete transaction
- [x] implement logic in local storage
- [x] update storybook
- [x] create PR

## Size

(small)
