### ISSUE TITLE
Add Notes and Tags to TransactionFormInput, include verification

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#19]
## Value statement - a requirement, not a solution

As a user
I need to be able to add notes to transactions so that I know what I spend my money on. In addition to that, I need to be able to add tags to my transactions to gain a quick overview over my budget history. 

## Acceptance criteria

- [x] The user must be able to input short notes, max. word-length: 100)
- [x] The user must be able to choose from a pre-defined amount of tags to classify his/her transaction
- [x] to start with, the user is allowed to choose a maximum amount of 1 tag per transaction entry. 
- [x] both features must be displayed in the individual transaction entry

## Tasks

- [x] create feature branch
- [x] create further input field for notes-input in form component
- [x] show notes in individual transaction item
- [x] create 5-6 pre-defined tags
- [x] create validation for notes-entry and tag-entry
- [x] ensure both values are passed to local storage and to components further down (transaction-list, individual transaction-entry)
- [x] update storybook

## Size

large
