### ISSUE TITLE
Add transaction logic and form validation

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#2]
## Value statement - a requirement, not a solution
As a user I need to be able to input income and spendings to the budget app in a standradized manner, so that the data output looks clean and easy to read.

## Description (Text, Scribble, Wireframe, Design)

![Budget Input   List of Transactions(1)](https://user-images.githubusercontent.com/67912360/91643143-fcdea180-ea30-11ea-8bba-fcc487082eb1.png)

## Acceptance criteria
- [x] User may enter only positive values
- [x] The user may enter any numerical value before the comma and two digits are allowed after the comma 
- [x] For the purpose of consistency, two digits after the decimal point are always displayed (e.g. a transaction of 20,00 Euro will never be displayed as simply 20 Euro)
- [x] The user is not allowed to enter any other value except decimal numbers and a separator 
- [x] The user is allowed to enter , as a separator. In local storage, the separator must be translated to . to enable adding/substracting values for the monthly balance. Before displaying indivudial transactions, the . must again be translated to , for the sake of consistency. 
- [x] Zero as a value is allowed before and after the comma, but superfluous zeros will be cut out (e.g. a transaction input by the user such as 000020,0000 Euro will be transformed to 20,00 Euro)
- [x] The user must input a number in order to be able to add the transaction --> empty input field is not permitted. 
- [x] White spaces must be cut out before saving to local storage 
- [x] Transaction must have a unique identifier apart from the timestamp 

## Tasks
- [x] create feature branch
- [x] research Regular Expressions
- [x] rewrite component test in jest
- [x] add functional logic to app as described in the acceptance criteria
- [x] add expected Prop Types
- [x] add uuidv4 in order to have a unique identifier for a transaction 

## Size
 large
