### ISSUE TITLE
Refactor Code: New Dashboard, Add Transaction Page

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#24]
## Value statement - a requirement, not a solution

As a user I need a well structured app, which is divided into different subpages from a functional and content wise point of view. I also need to be able to navigate easily through the different pages.  

## Description (Text, Scribble, Wireframe, Design)
<img width="694" alt="Bildschirmfoto 2020-09-18 um 14 11 57" src="https://user-images.githubusercontent.com/67912360/93596015-023c6580-f9b9-11ea-9216-29a940ede2b4.png">

## Acceptance criteria

- [x] create a new page containing only the monthly balance and the list of transactions
- [x] rename Page containing only the form component to Add Transaction Page
- [x] user must be able to navigate between the pages

## Tasks

- [x] create feature branch
- [x] create new dashboard page and move Monthly Baalance and TransactionList to page
- [x] rename TransactionInputPage to AddTransactionPage
- [x] refactor code on former TransactionInputPage
- [x] implement React Router and Nav-Elements
- [x] check state management
- [x] write PR

## Size

(medium)
