### ISSUE TITLE
Add option to edit entries

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#27]
## Value statement - a requirement, not a solution

As a user, I need to be able to edit transaction entries and update data within a transaction. 

## Acceptance criteria

- [x] the user must be able to edit transaction entries by clicking on a button
- [x] the transaction must be loaded into the form component, so that the user can see value, tag and notes and edit only specific data
- [x] within the form component, a click on reset must reset the form to the state the transaction was in before the user started to change individual form entries 
- [x] on the transaction overview page, the edited transaction must remain at the same place within the list (same index as before)

## Tasks

- [x] create feature branch
- [x] add Edit-Button with appropriate svg
- [x] place edit-button within transaction-component
- [x] add new edit-page 
- [x] add routing to new page
- [x] work out how to transfer transaction data to edit page
- [x] edit form component so that it displays not only empty strings as initial values but can also be re-initialized with existing transaction data
- [x] reassemble transaction object and transfer updated transaction back into the transactions-state on Overview Page
- [x] ensure that the updated value is included in the sum of all transactions

## Size
large
