### ISSUE TITLE
Add Transaction Input Form without Funcitonality 

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#3]
## Value statement - a requirement, not a solution
As a user I need to be able to input income and spendings to the budget app.
In order to be able to do that, I need a labled input field, a button to toggle between input and spending and a button to add a new transaction. 

## Description (Text, Scribble, Wireframe, Design)
![Budget Input   List of Transactions(1)](https://user-images.githubusercontent.com/67912360/91643283-0caab580-ea32-11ea-9dc4-92b9e6a48bc9.png)

## Acceptance criteria
implement as shown in wireframe: 
- [x] toggle-button for spending and income
- [x] button to add a new transaction
- [x] input with a placeholder text and a lable to clarify the currency 
- [x] Add lable before monthly balance
- [x] Let List of Transactions be displayed below the form

## Tasks
- [x] create feature branch
- [x] add toggle-button, add-button and input-field with placeholder-text to app
- [x] add minmal component tests 

## Size
small
