### ISSUE TITLE
Add Donut-Chart with tag-color-coding for a better overview over income/spending history

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#35]
## Value statement - a requirement, not a solution

As a user
I need an overview over my monthly budget that is easy to grasp and depicts all existing spending categories, 
so that I am in control of my finances. 

## Description (Text, Scribble, Wireframe, Design)

- donut-chart with color coding from tags/categories

## Acceptance criteria

- [ ] spendings must be dynamically rendered into the donut chart
- [ ] values must be displayed as percentages and actual sums within the categories
- [ ] the color-coding must be explained below the donut chart
- [ ] the donut-chart must be located on the home-screen

## Tasks

- [ ] create feature branch
- [ ] take a look at victory to create the chart
- [ ] create new homepage with navigation to "Transaction Overview Page" and "Add Transaction Page", if neccessary, add NavBar to all pages
- [ ] add unit test for chart
- [ ] add integration test for page
- [ ] Create PR

## Size

medium
