### ISSUE TITLE
Filter transactions by month

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#37]
## Value statement - a requirement, not a solution

As a  user I need to have an overview over my personal finances. 
For this day-to-day overview, my monthly budget is most relevant to me. 

## Description (Text, Scribble, Wireframe, Design)

- [ ] On the transaction overview page, only the transactions from the current month will be listed

## Acceptance criteria

- [ ] List shows only transactions from current month

## Tasks

- [ ] create feature branch
- [ ] add filter by date to local storage, so that getTransactionEntries (see services/transactionServices) will give back transactions of the current month to be displayed on the overview page
- [ ] adjust unit test
- [ ] adjust integration test
- [ ] create PR

## Size

medium
