### ISSUE TITLE
Add 'filter by tag' to Detailed Transaction Page

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#38]
## Value statement - a requirement, not a solution

As a user I need to have an overview over my spending history by spending category, so that I can addjust my spending habits if neccessary and notice deviations from my regular spending habits. 

## Description (Text, Scribble, Wireframe, Design)

- [ ] The user can click on a "Filter"-svg and is presented with the option to filter by tag (radio-buttons)

## Acceptance criteria

- [ ] The user must be able to select a tag category and is shown all transactions from that exact month with the relevant tag, as well as the total sum of spendings for that category. He/she can compare that sum to the remaining monthly budget. 

## Tasks

- [ ] create feature branch
- [ ] search for filter svg
- [ ] create radio buttons with color coding similar to tags and a further button with the text "Show all". If clicked(=filter is active), the border-color will become the background-color and the font-color will turn to white. 
- [ ] write filter-function for transaction-overview-page and/or services/transactionServices
- [ ] adjust integration test
- [ ] write PR

## Size
large
