### ISSUE TITLE
Add transaction history 

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#39]
## Value statement - a requirement, not a solution

As a user I want to compare my spending history to identify trends in my spending habits and adjust them if neccessary. 

## Description (Text, Scribble, Wireframe, Design)

- [ ] The user must be able to navigate between months to show the transaction history. Sorting functions (sort by tag) can still be applied. Navigation is going to take place by two arrows next to the sub-headline in the header-component

## Acceptance criteria

- [ ] see above 

## Tasks

- [ ] create feature branch
- [ ] seach for arrow-svgs
- [ ] implement sorting logic in services/transactionServices
- [ ] work on transition animation between months
- create PR

## Size

 large
