### ISSUE TITLE
Setup Capstone Project and install dependencies

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#5]

**Comment by annaleaschroeder** [comment]
## Tasks: 

- [x] Setup new Git Repository
- [x] install react
- [x] install storybook
- [x] install jest
- [x] install prop-types
- [x] install react router
- [x] install styled-components
- [x] install uuidv4
- [x] write .prettierrc
