### ISSUE TITLE
Add toggle logic to switch between type of transaction

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#7]
## Value statement - a requirement, not a solution
As a user
I need to switch between entering spending and income into my budget app. 

## Description (Text, Scribble, Wireframe, Design)

![Budget Input   List of Transactions(1)](https://user-images.githubusercontent.com/67912360/91689434-67442e80-eb64-11ea-8607-81d0273b309c.png)

## Acceptance criteria
- [x] on toggeling, the user must be able to switch beween income and spending input
- [x] the user must see on fist glance what type of input he/she is seeing at this moment. 

## Tasks
- [x] create feature branch
- [x] adjust unit-test
- [x] modify storybook-component as neccessary
- [x] add toggle-logic to component
- [x] add expected Prop Types
- [x] write PR

## Size
small
