### ISSUE TITLE
Implement local storage

### ISSUE THREAD

**Issue by annaleaschroeder** [annaleaschroeder/capstone-project#9]
## Value statement - a requirement, not a solution
As a user
I need to be able to save my transaction history
so that I can access it at any time

## Acceptance criteria
- [x] saved object must contain: timestamp (when was the transaction added), time of transaction, an id and the type of transaction as specified with the toggle button (income/spending).

## Tasks
- [x] create feature branch 
- [x] research on implementation of local storage (1 hour max) 
- [x] implement local storage to project
- [x] write PR. 

## Size
medium
